version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: docker-mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-mock-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    networks:
      - app-network
  cep-api-docker:
    build:
      dockerfile: DockerFile
    image: cep-api-docker-image
    ports:
        - "8090:8090"
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge